// Messages for 25 users
export const MESSAGES = {
  1: [
    { from: "Ali", text: "Hey, how’s it going?" },
    { from: "You", text: "Good, how about you?" },
    { from: "Ali", text: "Just busy with work, as usual!" },
    { from: "You", text: "Same here! Anything new?" },
    { from: "Ali", text: "Well, I’m finally getting a break! You should too 😜" },
    { from: "You", text: "Lucky you! I’ll catch up when I can, don’t rub it in!" },
    { from: "Ali", text: "Haha, I’m just messing with you! We should hang out soon." },
    { from: "You", text: "For sure! Let’s plan something next weekend!" },
  ],
  2: [
    { from: "Ahmed", text: "Hi there! What’s new? You’ve been MIA lately." },
    { from: "You", text: "Not much, just buried under work. You know how it is." },
    { from: "Ahmed", text: "That sounds interesting! Or are you just avoiding me again? 😏" },
    { from: "You", text: "Whoa, what? I’m literally always busy! You know that! 😅" },
    { from: "Ahmed", text: "Sure, sure... Maybe next time I’ll believe you! But seriously, we need to catch up. How about dinner this Friday?" },
    { from: "You", text: "Haha, okay, you got me. Dinner sounds great. But you’re paying this time!" },
    { from: "Ahmed", text: "Deal! But only if you promise not to order the most expensive thing on the menu. 😜" },
    { from: "You", text: "No promises! You know I have expensive taste! 😎" },
  ],
  3: [
    { from: "Aisha", text: "What’s your favorite movie? I need recommendations for movie night!" },
    { from: "You", text: "I’m obsessed with 'Inception'! The plot is mind-blowing." },
    { from: "Aisha", text: "Oh, that’s a great one! But the ending was a bit too much for me. I need closure!" },
    { from: "You", text: "Really? I thought the ambiguity made it perfect. It keeps you thinking!" },
    { from: "Aisha", text: "I guess we’ll have to agree to disagree. But I’ll give it another shot. Maybe you can explain it to me! 😂" },
    { from: "You", text: "Deal! Let’s grab coffee soon and debate it more. I’ll bring my whiteboard for diagrams! 😉" },
    { from: "Aisha", text: "Haha, you’re such a nerd. But I love it. Coffee it is!" },
    { from: "You", text: "Perfect! See you then. Don’t forget to bring your thinking cap! 🧠" },
  ],
  4: [
    { from: "Bilal", text: "What’s your favorite food? I’m starving and need ideas!" },
    { from: "You", text: "I love Italian food, especially pasta. Carbonara is my weakness!" },
    { from: "Bilal", text: "Nice! I’m all about pizza. Nothing beats a good slice." },
    { from: "You", text: "Oh, me too! Pizza is the ultimate comfort food." },
    { from: "Bilal", text: "We need a pizza and pasta night soon. What do you think?" },
    { from: "You", text: "I’m in, but only if I pick the pasta. You always go for the weird toppings!" },
    { from: "Bilal", text: "Deal! But I’m picking the pizza toppings. And no complaining!" },
    { from: "You", text: "Haha, okay fine. But no pineapple on the pizza! That’s a deal-breaker. 😆" },
  ],
  5: [
    { from: "Fatima", text: "Long time no see! How have you been?" },
    { from: "You", text: "Yeah, it’s been way too long! I’m good, just busy with life. How about you?" },
    { from: "Fatima", text: "Same here. We should catch up soon. I miss our hangouts!" },
    { from: "You", text: "Definitely! Let’s plan something. I miss our late-night talks and endless laughter." },
    { from: "Fatima", text: "Remember when we used to talk for hours? Those were the best times." },
    { from: "You", text: "How could I forget? You always had the best stories!" },
    { from: "Fatima", text: "And you always used to steal the last piece of dessert. Still guilty of that?" },
    { from: "You", text: "Haha, guilty as charged! Some things never change. 😜" },
  ],
  6: [
    { from: "Hassan", text: "I saw your new project, it looks amazing! You’ve outdone yourself." },
    { from: "You", text: "Thanks, Hassan! Still a work in progress, but I’m happy with how it’s turning out." },
    { from: "Hassan", text: "You’re being modest. It’s seriously impressive. Keep it up!" },
    { from: "You", text: "Appreciate it! Hoping to wrap it up soon. It’s been a grind." },
    { from: "Hassan", text: "I bet you’ll finish it in no time. You’re a machine when it comes to this stuff!" },
    { from: "You", text: "Haha, I wish! It’s been a bit of a struggle lately, but I’m pushing through." },
    { from: "Hassan", text: "Nah, I know you’ve got this. Just don’t burn yourself out. Take breaks!" },
    { from: "You", text: "Thanks for the advice! You always know how to motivate me. Let’s grab coffee soon!" },
  ],
  7: [
    { from: "Hussain", text: "Hey! What are you up to? I’m bored out of my mind." },
    { from: "You", text: "Just relaxing at home. Finally taking a break after a long week." },
    { from: "Hussain", text: "Nice! Enjoy your downtime. You deserve it." },
    { from: "You", text: "Thanks! What about you? Any plans?" },
    { from: "Hussain", text: "Actually, I’m thinking of coming over. You’re not too busy, right?" },
    { from: "You", text: "Haha, not at all! You know I’m always up for a visit. Bring your A-game, though!" },
    { from: "Hussain", text: "Cool, I’ll bring the snacks! But you better not make me wait for food this time!" },
    { from: "You", text: "Haha, no promises! You might have to wait again. Patience is a virtue, my friend! 😉" },
  ],
  8: [
    { from: "Ibrahim", text: "What book are you reading these days? I need something new." },
    { from: "You", text: "Just finished 'The Silent Patient'. It’s a thriller—so good!" },
    { from: "Ibrahim", text: "I’ve heard of it! Was it as good as they say?" },
    { from: "You", text: "Definitely! The twist at the end blew my mind. I couldn’t put it down." },
    { from: "Ibrahim", text: "You’re making me want to read it now. I’ll check it out this weekend!" },
    { from: "You", text: "You won’t regret it! Let me know what you think when you’re done." },
    { from: "Ibrahim", text: "Will do! Maybe we can start a mini book club. What do you think?" },
    { from: "You", text: "I’m in! Let’s make it happen. First meeting at my place? 😊" },
  ],
  9: [
    { from: "Junaid", text: "How’s your weekend going? Anything exciting?" },
    { from: "You", text: "Pretty chill, just rewatching 'Interstellar'. It’s one of my favorites!" },
    { from: "Junaid", text: "Great choice! But you know it’s a bit complicated, right? I still don’t get half of it. 😂" },
    { from: "You", text: "I know! It takes some thinking, but that’s what makes it awesome. The science is mind-blowing." },
    { from: "Junaid", text: "Fair enough, but I need someone to explain it to me. How about we watch it together sometime?" },
    { from: "You", text: "Haha, deal! I’ll bring the popcorn, you bring the questions. Sound good?" },
    { from: "Junaid", text: "Perfect! Let’s make it a movie night. Maybe next weekend?" },
    { from: "You", text: "Done! I’ll clear my schedule. Prepare to have your mind blown! 🚀" },
  ],
  10: [
    { from: "Khalid", text: "How was your trip to the mountains? I need details!" },
    { from: "You", text: "It was amazing! So refreshing. The views were breathtaking." },
    { from: "Khalid", text: "That’s awesome! I need to do that sometime. I’ve been stuck in the city too long." },
    { from: "You", text: "Definitely! You should. It’s the perfect escape." },
    { from: "Khalid", text: "Next time, we should go together! You know I hate going solo." },
    { from: "You", text: "Haha, deal! But only if you stop making me carry all the gear this time!" },
    { from: "Khalid", text: "Only if you bring the snacks! 😎" },
    { from: "You", text: "It’s a deal! You bring the gear, I’ll bring the food. Adventure awaits! 🏔️" },
  ],
  11: [
    { from: "Laila", text: "What’s your favorite hobby? I need a new one!" },
    { from: "You", text: "I love photography! It’s my creative outlet." },
    { from: "Laila", text: "That’s so cool! What do you like to shoot?" },
    { from: "You", text: "Nature, mostly. There’s something magical about capturing landscapes." },
    { from: "Laila", text: "You should show me some of your pictures sometime! I’d love to see your work." },
    { from: "You", text: "I’d love to! I just need to sort through them first. I have so many!" },
    { from: "Laila", text: "I’m sure they’re amazing. Stop being modest! Let’s plan a photo walk soon." },
    { from: "You", text: "Haha, alright, I’ll send you some soon. And a photo walk sounds perfect! 📸" },
  ],
  12: [
    { from: "Muneeb", text: "What are your thoughts on the new tech trends? AI is everywhere now!" },
    { from: "You", text: "They’re exciting, especially AI. It’s changing the game in so many industries." },
    { from: "Muneeb", text: "I agree! It’s fascinating, but also a bit scary. What if it takes over everything?" },
    { from: "You", text: "True, but if it helps with productivity and innovation, I’m all for it. We just need to use it responsibly." },
    { from: "Muneeb", text: "Yeah, that’s a good point. Let’s hope for the best. The future is looking bright!" },
    { from: "You", text: "For sure! We’re heading into interesting times. Let’s stay ahead of the curve!" },
    { from: "Muneeb", text: "Agreed. Maybe we should take a course on AI together. What do you think?" },
    { from: "You", text: "I’m in! Let’s do it. Knowledge is power, after all! 💡" },
  ],
  13: [
    { from: "Nadia", text: "Have you watched the latest episode?" },
    { from: "You", text: "Yes! It was intense." },
    { from: "Nadia", text: "I know, right? Can’t wait for the next one!" },
    { from: "You", text: "Same here, it’s getting really good!" },
    { from: "Nadia", text: "I swear, the cliffhanger is killing me!" },
    { from: "You", text: "I know! How are they going to resolve it?" },
    { from: "Nadia", text: "No idea, but I’m so ready for the next episode!" },
    { from: "You", text: "Same! Let’s watch it together when it airs!" },
  ],
  14: [
    { from: "Omar", text: "How are you? Long time no see!" },
    { from: "You", text: "I’m good, just been busy with work." },
    { from: "Omar", text: "I get that. We should hang out soon." },
    { from: "You", text: "Definitely, let’s plan something!" },
    { from: "Omar", text: "I miss our old times, man. Let’s catch up soon!" },
    { from: "You", text: "I miss it too, we used to have so much fun!" },
    { from: "Omar", text: "No more excuses, let's go for a game night soon!" },
    { from: "You", text: "Done! I'll bring the snacks!" },
  ],
  15: [
    { from: "Parveen", text: "How was your weekend getaway?" },
    { from: "You", text: "It was great! Very relaxing." },
    { from: "Parveen", text: "Sounds like a good time!" },
    { from: "You", text: "Yeah, it was much needed." },
    { from: "Parveen", text: "Was the weather perfect for it?" },
    { from: "You", text: "Definitely! Just the right amount of sunshine." },
    { from: "Parveen", text: "Jealous! I need a getaway soon." },
    { from: "You", text: "We should plan one together! It’d be fun!" },
  ],
  16: [
    { from: "Qasim", text: "Have you tried the new restaurant?" },
    { from: "You", text: "Not yet, but I’ve heard great things." },
    { from: "Qasim", text: "You should check it out, the food is amazing!" },
    { from: "You", text: "I’ll definitely try it soon!" },
    { from: "Qasim", text: "You better! I’m already craving their food again 😂" },
    { from: "You", text: "Haha, okay, okay, I’ll make a reservation for us!" },
    { from: "Qasim", text: "Now that’s what I’m talking about! Let’s go!" },
    { from: "You", text: "It’s a date! 😎" },
  ],
  17: [
    { from: "Rana", text: "What’s your favorite TV show?" },
    { from: "You", text: "I’m into 'Breaking Bad' right now!" },
    { from: "Rana", text: "Such a classic!" },
    { from: "You", text: "Agreed! It’s so intense." },
    { from: "Rana", text: "The plot twists never get old." },
    { from: "You", text: "I know! Every episode keeps me on the edge of my seat." },
    { from: "Rana", text: "I need to rewatch it now!" },
    { from: "You", text: "We should rewatch it together sometime!" },
  ],
  18: [
    { from: "Sara", text: "What are you up to?" },
    { from: "You", text: "Just finished working, now chilling." },
    { from: "Sara", text: "Nice! You deserve a break." },
    { from: "You", text: "Haha, thanks! What about you?" },
    { from: "Sara", text: "Same here, just enjoying some downtime." },
    { from: "You", text: "We should do something fun soon!" },
    { from: "Sara", text: "For sure, I’m in!" },
    { from: "You", text: "Let’s plan something this weekend!" },
  ],
};


// Users list for 25 users
export const USERS = [
  { id: 1, name: "Ali", avatar: "A" },
  { id: 2, name: "Ahmed", avatar: "Ah" },
  { id: 3, name: "Aisha", avatar: "Ai" },
  { id: 4, name: "Bilal", avatar: "B" },
  { id: 5, name: "Fatima", avatar: "F" },
  { id: 6, name: "Hassan", avatar: "H" },
  { id: 7, name: "Hussain", avatar: "Hu" },
  { id: 8, name: "Ibrahim", avatar: "I" },
  { id: 9, name: "Junaid", avatar: "J" },
  { id: 10, name: "Khalid", avatar: "K" },
  { id: 11, name: "Laila", avatar: "L" },
  { id: 12, name: "Muneeb", avatar: "M" },
  { id: 13, name: "Nadia", avatar: "N" },
  { id: 14, name: "Omar", avatar: "O" },
  { id: 15, name: "Parveen", avatar: "P" },
  { id: 16, name: "Qasim", avatar: "Q" },
  { id: 17, name: "Rana", avatar: "R" },
  { id: 18, name: "Sara", avatar: "S" },

];
