// Messages for 25 users
export const MESSAGES = {
  1: [
    { from: "Ali", text: "Hey, how’s it going?" },
    { from: "You", text: "Good, how about you?" },
    { from: "Ali", text: "Just busy with work, as usual!" },
    { from: "You", text: "Same here! Anything new?" },
    { from: "Ali", text: "Well, I’m finally getting a break! You should too 😜" },
    { from: "You", text: "Lucky you! I’ll catch up when I can, don’t rub it in!" },
    { from: "Ali", text: "Haha, I’m just messing with you! We should hang out soon." },
    { from: "You", text: "For sure! Let’s plan something next weekend!" },
  ],
  2: [
    { from: "Ahmed", text: "Hi there! What’s new?" },
    { from: "You", text: "Not much, just working on some stuff." },
    { from: "Ahmed", text: "That sounds interesting!" },
    { from: "You", text: "Yeah, it's been keeping me busy." },
    { from: "Ahmed", text: "I don’t believe you, you're just avoiding me!" },
    { from: "You", text: "Whoa, what? I’m literally always busy! 😅" },
    { from: "Ahmed", text: "Sure, sure... Maybe next time I’ll believe you! 😜" },
    { from: "You", text: "Haha, we’ll see about that!" },
  ],
  3: [
    { from: "Aisha", text: "What’s your favorite movie?" },
    { from: "You", text: "I really liked 'Inception'!" },
    { from: "Aisha", text: "Oh, that’s a great one!" },
    { from: "You", text: "Yeah, the plot is mind-blowing!" },
    { from: "Aisha", text: "True, but the ending was a bit too much for me." },
    { from: "You", text: "Really? I thought it was perfect. The ambiguity made it so much better!" },
    { from: "Aisha", text: "I guess we’ll have to agree to disagree 😂" },
    { from: "You", text: "Fair enough! Let’s grab some coffee soon and debate it more 😉" },
  ],
  4: [
    { from: "Bilal", text: "What’s your favorite food?" },
    { from: "You", text: "I love Italian food, especially pasta!" },
    { from: "Bilal", text: "Nice! I love pizza." },
    { from: "You", text: "Oh, me too! Best comfort food!" },
    { from: "Bilal", text: "We need a pizza and pasta night soon, what do you think?" },
    { from: "You", text: "I’m in, but only if I pick the pasta!" },
    { from: "Bilal", text: "Deal! But I’m picking the pizza toppings." },
    { from: "You", text: "Haha, okay fine. But no pineapple on the pizza! 😆" },
  ],
  5: [
    { from: "Fatima", text: "Long time no see!" },
    { from: "You", text: "Yeah, it's been a while!" },
    { from: "Fatima", text: "We should catch up soon." },
    { from: "You", text: "Definitely! Let’s plan something." },
    { from: "Fatima", text: "I miss our hangouts, remember when we used to talk for hours?" },
    { from: "You", text: "How could I forget? Those were the days!" },
    { from: "Fatima", text: "You always used to steal the last piece of dessert though!" },
    { from: "You", text: "Haha, guilty as charged! 😜" },
  ],
  6: [
    { from: "Hassan", text: "I saw your new project, it looks great!" },
    { from: "You", text: "Thanks! Still working on it." },
    { from: "Hassan", text: "Keep it up, it's really impressive." },
    { from: "You", text: "Appreciate it! Hoping to finish soon." },
    { from: "Hassan", text: "I bet you’ll finish it in no time. You’re a machine!" },
    { from: "You", text: "Haha, I wish! It’s been a bit of a struggle lately." },
    { from: "Hassan", text: "Nah, I know you’ve got this. Just don’t burn yourself out!" },
    { from: "You", text: "Thanks for the advice! You always know how to motivate me!" },
  ],
  7: [
    { from: "Hussain", text: "Hey! What are you up to?" },
    { from: "You", text: "Just relaxing at home." },
    { from: "Hussain", text: "Nice! Enjoy your time." },
    { from: "You", text: "Thanks! You too!" },
    { from: "Hussain", text: "Actually, I’m thinking of coming over. You’re not too busy, right?" },
    { from: "You", text: "Haha, not at all! You know I’m always up for a visit." },
    { from: "Hussain", text: "Cool, I’ll bring the snacks! But you better not make me wait for food this time!" },
    { from: "You", text: "Haha, no promises! You might have to wait again 😉" },
  ],
  8: [
    { from: "Ibrahim", text: "What book are you reading these days?" },
    { from: "You", text: "Just finished a thriller novel." },
    { from: "Ibrahim", text: "Oh nice! Which one?" },
    { from: "You", text: "It’s called 'The Silent Patient'!" },
    { from: "Ibrahim", text: "I’ve heard of it! Was it as good as they say?" },
    { from: "You", text: "Definitely! The twist at the end was mind-blowing!" },
    { from: "Ibrahim", text: "You’re making me want to read it now. I’ll check it out!" },
    { from: "You", text: "You won’t regret it! It’s a page-turner!" },
  ],
  9: [
    { from: "Junaid", text: "How’s your weekend going?" },
    { from: "You", text: "Pretty chill, just watching a movie." },
    { from: "Junaid", text: "Sounds fun! What movie?" },
    { from: "You", text: "'Interstellar', one of my favorites!" },
    { from: "Junaid", text: "Great choice! But you know it’s a bit complicated, right?" },
    { from: "You", text: "I know! It takes some thinking, but that’s what makes it awesome." },
    { from: "Junaid", text: "Fair enough, but I still don’t get half of it 😂" },
    { from: "You", text: "Haha, no worries! We can watch it together sometime and figure it out!" },
  ],
  10: [
    { from: "Khalid", text: "How was your trip to the mountains?" },
    { from: "You", text: "It was amazing! Really refreshing." },
    { from: "Khalid", text: "That’s awesome! I need to do that sometime." },
    { from: "You", text: "Definitely! You should." },
    { from: "Khalid", text: "Next time, we should go together! You know I hate going solo." },
    { from: "You", text: "Haha, deal! But only if you stop making me carry all the gear this time!" },
    { from: "Khalid", text: "Only if you bring the snacks! 😎" },
    { from: "You", text: "It’s a deal! You bring the gear, I’ll bring the food!" },
  ],
  11: [
    { from: "Laila", text: "What’s your favorite hobby?" },
    { from: "You", text: "I love photography!" },
    { from: "Laila", text: "That’s cool! What do you like to shoot?" },
    { from: "You", text: "Nature, mostly." },
    { from: "Laila", text: "You should show me some of your pictures sometime!" },
    { from: "You", text: "I’d love to! I just need to sort through them first." },
    { from: "Laila", text: "I’m sure they’re amazing. Stop being modest!" },
    { from: "You", text: "Haha, alright, I’ll send you some soon!" },
  ],
  12: [
    { from: "Muneeb", text: "What are your thoughts on the new tech trends?" },
    { from: "You", text: "They’re exciting, especially AI." },
    { from: "Muneeb", text: "I agree! It's changing everything." },
    { from: "You", text: "Definitely, the future is looking bright!" },
    { from: "Muneeb", text: "I just hope it doesn’t take over everything, you know?" },
    { from: "You", text: "True, but if it helps with productivity, I’m all for it!" },
    { from: "Muneeb", text: "Yeah, that’s a good point. Let’s hope for the best!" },
    { from: "You", text: "For sure, we’re heading into interesting times!" },
  ],
  13: [
    { from: "Nadia", text: "Have you watched the latest episode?" },
    { from: "You", text: "Yes! It was intense." },
    { from: "Nadia", text: "I know, right? Can’t wait for the next one!" },
    { from: "You", text: "Same here, it’s getting really good!" },
    { from: "Nadia", text: "I swear, the cliffhanger is killing me!" },
    { from: "You", text: "I know! How are they going to resolve it?" },
    { from: "Nadia", text: "No idea, but I’m so ready for the next episode!" },
    { from: "You", text: "Same! Let’s watch it together when it airs!" },
  ],
  14: [
    { from: "Omar", text: "How are you? Long time no see!" },
    { from: "You", text: "I’m good, just been busy with work." },
    { from: "Omar", text: "I get that. We should hang out soon." },
    { from: "You", text: "Definitely, let’s plan something!" },
    { from: "Omar", text: "I miss our old times, man. Let’s catch up soon!" },
    { from: "You", text: "I miss it too, we used to have so much fun!" },
    { from: "Omar", text: "No more excuses, let's go for a game night soon!" },
    { from: "You", text: "Done! I'll bring the snacks!" },
  ],
  15: [
    { from: "Parveen", text: "How was your weekend getaway?" },
    { from: "You", text: "It was great! Very relaxing." },
    { from: "Parveen", text: "Sounds like a good time!" },
    { from: "You", text: "Yeah, it was much needed." },
    { from: "Parveen", text: "Was the weather perfect for it?" },
    { from: "You", text: "Definitely! Just the right amount of sunshine." },
    { from: "Parveen", text: "Jealous! I need a getaway soon." },
    { from: "You", text: "We should plan one together! It’d be fun!" },
  ],
  16: [
    { from: "Qasim", text: "Have you tried the new restaurant?" },
    { from: "You", text: "Not yet, but I’ve heard great things." },
    { from: "Qasim", text: "You should check it out, the food is amazing!" },
    { from: "You", text: "I’ll definitely try it soon!" },
    { from: "Qasim", text: "You better! I’m already craving their food again 😂" },
    { from: "You", text: "Haha, okay, okay, I’ll make a reservation for us!" },
    { from: "Qasim", text: "Now that’s what I’m talking about! Let’s go!" },
    { from: "You", text: "It’s a date! 😎" },
  ],
  17: [
    { from: "Rana", text: "What’s your favorite TV show?" },
    { from: "You", text: "I’m into 'Breaking Bad' right now!" },
    { from: "Rana", text: "Such a classic!" },
    { from: "You", text: "Agreed! It’s so intense." },
    { from: "Rana", text: "The plot twists never get old." },
    { from: "You", text: "I know! Every episode keeps me on the edge of my seat." },
    { from: "Rana", text: "I need to rewatch it now!" },
    { from: "You", text: "We should rewatch it together sometime!" },
  ],
  18: [
    { from: "Sara", text: "What are you up to?" },
    { from: "You", text: "Just finished working, now chilling." },
    { from: "Sara", text: "Nice! You deserve a break." },
    { from: "You", text: "Haha, thanks! What about you?" },
    { from: "Sara", text: "Same here, just enjoying some downtime." },
    { from: "You", text: "We should do something fun soon!" },
    { from: "Sara", text: "For sure, I’m in!" },
    { from: "You", text: "Let’s plan something this weekend!" },
  ],
};


// Users list for 25 users
export const USERS = [
  { id: 1, name: "Ali", avatar: "A" },
  { id: 2, name: "Ahmed", avatar: "Ah" },
  { id: 3, name: "Aisha", avatar: "Ai" },
  { id: 4, name: "Bilal", avatar: "B" },
  { id: 5, name: "Fatima", avatar: "F" },
  { id: 6, name: "Hassan", avatar: "H" },
  { id: 7, name: "Hussain", avatar: "Hu" },
  { id: 8, name: "Ibrahim", avatar: "I" },
  { id: 9, name: "Junaid", avatar: "J" },
  { id: 10, name: "Khalid", avatar: "K" },
  { id: 11, name: "Laila", avatar: "L" },
  { id: 12, name: "Muneeb", avatar: "M" },
  { id: 13, name: "Nadia", avatar: "N" },
  { id: 14, name: "Omar", avatar: "O" },
  { id: 15, name: "Parveen", avatar: "P" },
  { id: 16, name: "Qasim", avatar: "Q" },
  { id: 17, name: "Rana", avatar: "R" },
  { id: 18, name: "Sara", avatar: "S" },

];
